### ISSUE TITLE
Error: Port is not open

### ISSUE THREAD

**Issue by Jo-rauh** [node-enocean/node-red-contrib-enocean#4]
Hi Holger, Hi Nabbl,

thank you very much for realising the implementation in node red so quickly. I copied the example flow, and in the flow there is written "connected" under the node but unfortunately i get the Error output : Port is not open. Can you help me to solve this problem? Thank you very much! Great Work!

**Comment by nabbl** [comment]
Hi,

A bit more information would be great: Device? Hardware? OS? Enocean Hat or USB stick?

Usually this error pops up on raspberry PIs where the serial port is not open because it is blocked by the serialport console.

**Comment by Jo-rauh** [comment]
Hi,

sorry. I use the Raspberry pi 3 with Noobs and the Enocean Pi HAT. Can you tell me what i have to do to open this port? That would be nice. Thank you very much!

**Comment by nabbl** [comment]
So I am not 100% sure this is working on Noobs because I have almost the same setup but I am using Raspbian Jessie. There are problems with the Raspi3 and the enocean hat. You need to do follow the following steps (BEWARE THIS DISABLES BLUETOOTH):

**Step1:**
` sudo raspi-config`
select 9 Advanced options
A8 Disable Serial

If you cannot see a number 9. Just go to the interface options (number 5) and activate the `serialport.

**Step2**
`sudo nano /boot/config.txt`
Insert the following line in the end of the file:
`dtoverlay=pi3-disable-bt`
save and exit the file.

**Step3**
`sudo systemctl disable hciuart`

**Step4**
`sudo systemctl mask serial-getty@ttyAMA0.service`

**Step5**
`sudo reboot`

**Comment by nabbl** [comment]
Were you able to fix the problem?

**Comment by Jo-rauh** [comment]
Sorry. I had no time to work on it. Now i set up a new rpi with raspian stretch. I always get at first the message in the debug window "Error port is not open" but I receive data now (data object) . I don't know what the problem with the port is... Do you have any suggestion to get the sensor value out of the data object? Thank you very much and sorry one more time for answering so late!
